#!/bin/bash
# Bug Hunter - Generate Report
# Usage: ./report.sh <target> [data_dir]

TARGET=$1
DATA_DIR=${2:-/tmp/bug-hunter-$TARGET}
HUNT_DIR="$DATA_DIR/hunt-results"
REPORT="$HUNT_DIR/bug-hunter-report.md"

echo "# Bug Hunter Report - $TARGET
Generated: $(date)

---

## Executive Summary

This report contains findings from automated analysis of recon data for **$TARGET**.

---

## 🔐 Secrets Found

### AWS Keys
$(cat "$HUNT_DIR/secrets/aws_keys.txt" 2>/dev/null || echo "_None found_")

### JWT Tokens
$(cat "$HUNT_DIR/secrets/jwt.txt" 2>/dev/null || echo "_None found_")

### API Keys
$(cat "$HUNT_DIR/secrets/api_keys.txt" 2>/dev/null || echo "_None found_")

### S3 Buckets
$(cat "$HUNT_DIR/secrets/s3_buckets.txt" 2>/dev/null || echo "_None found_")

---

## 🎯 High Priority Endpoints

### Admin Panels
$(cat "$HUNT_DIR/endpoints/admin.txt" 2>/dev/null | head -20 || echo "_None found_")

### API Endpoints
$(cat "$HUNT_DIR/endpoints/api.txt" 2>/dev/null | head -20 || echo "_None found_")

### Authentication
$(cat "$HUNT_DIR/endpoints/auth.txt" 2>/dev/null | head -20 || echo "_None found_")

### File Upload
$(cat "$HUNT_DIR/endpoints/upload.txt" 2>/dev/null | head -20 || echo "_None found_")

---

## ⚡ Vulnerable Parameters

### XSS Test Points
$(cat "$HUNT_DIR/vulns/xss_params.txt" 2>/dev/null | head -20 || echo "_None found_")

### SQLi Test Points
$(cat "$HUNT_DIR/vulns/sqli_params.txt" 2>/dev/null | head -20 || echo "_None found_")

### SSRF Test Points
$(cat "$HUNT_DIR/vulns/ssrf_params.txt" 2>/dev/null | head -20 || echo "_None found_")

### LFI Test Points
$(cat "$HUNT_DIR/vulns/lfi_params.txt" 2>/dev/null | head -20 || echo "_None found_")

---

## 🔍 Subdomain Takeover Targets

### Dev/Staging
$(cat "$HUNT_DIR/takeover/dev_staging.txt" 2>/dev/null | head -20 || echo "_None found_")

### Cloud Resources
$(cat "$HUNT_DIR/takeover/cloud.txt" 2>/dev/null | head -20 || echo "_None found_")

---

## 📋 Recommended Testing Order

1. **Critical**: Test S3 buckets for public access
2. **Critical**: Test exposed AWS keys
3. **High**: Test admin panels for auth bypass
4. **High**: Test SQLi parameters
5. **High**: Test XSS parameters
6. **Medium**: Test SSRF/LFI parameters

---

## Next Steps

1. Verify each finding manually
2. Test exploitability with appropriate payloads
3. Document with screenshots and PoC
4. Submit to bug bounty program

---

*Generated by Bug Hunter Agent*
" > "$REPORT"

echo "[+] Report generated: $REPORT"

# Execute Python Dashboard compilation
DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$DIR/generate_dashboard.py" ]; then
    python3 "$DIR/generate_dashboard.py" "$TARGET" "$DATA_DIR" || echo "[-] Failed to generate Web Dashboard"
fi